### PR TITLE
Bump to 3.15.2

### PR DESCRIPTION
**Pull request by hadim**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hadim** [comment]
The CI will fail because of missing deps.

**Comment by hadim** [comment]
Blocked by:

- `aim-ui`: https://github.com/conda-forge/staged-recipes/pull/21651
- `aimrocks`: https://github.com/conda-forge/staged-recipes/pull/21653
- `rocksdb ==6.29.5`: https://github.com/conda-forge/rocksdb-feedstock/pull/48

**Comment by arkkln** [comment]
@hadim thanks for the contribution! This is huge!! Please feel free to let me know if you need any help.

**Comment by hadim** [comment]
The python 3.10 builds are blocked by https://github.com/conda-forge/restrictedpython-feedstock/pull/6

**Comment by hadim** [comment]
@gorarakelyan: we are quite close here. We only need this https://github.com/conda-forge/restrictedpython-feedstock/pull/6 to be merged and this PR should be good to go.

Windows builds are not available because of `aimrocks` (https://github.com/aimhubio/aimrocks/pull/22). Once available, the `rocksdb` conda forge package will need to be built against windows as well (I don't think I'll have time to build windows packages since I don't use them myself).

**Comment by hadim** [comment]
@gorarakelyan: I am skipping python 3.10 for now and will trigger a new build whenever https://github.com/conda-forge/restrictedpython-feedstock/pull/6 is merged.

You can merge here!

**Review by arkkln — APPROVED** [review]
lgtm

**Comment by hadim** [comment]
@gorarakelyan: I can't merge myself here.

**Comment by arkkln** [comment]
@hadim I will merge the PR now and open respective issues for:
- support for python later versions
- windows support

**Pull request merged**
